# Generated by Django 2.0.7 on 2019-06-16 18:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000), size=None),
        ),
    ]
