# Generated by Django 2.0.7 on 2019-06-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_auto_20190616_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
