# Generated by Django 2.0.7 on 2019-06-16 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_auto_20190616_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='img',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None),
        ),
    ]
