# Generated by Django 2.0.7 on 2019-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_auto_20190617_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='district',
            field=models.CharField(default='Kathmandu', max_length=20),
        ),
        migrations.AddField(
            model_name='attractions',
            name='province',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
