# Generated by Django 2.0.7 on 2019-06-18 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_auto_20190617_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('province', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=10000)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000), size=None)),
                ('url', models.URLField()),
                ('book', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
