# Generated by Django 2.0.7 on 2019-06-19 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='festivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('img', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000), size=None)),
            ],
        ),
    ]
