# Generated by Django 2.0.7 on 2019-06-19 16:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_festivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('img', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000), size=None)),
                ('district', models.CharField(max_length=100)),
                ('province', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='pubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('img', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000), size=None)),
                ('district', models.CharField(max_length=100)),
                ('province', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('img', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), size=None)),
                ('district', models.CharField(max_length=100)),
                ('province', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='img',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), null=True, size=None),
        ),
    ]
