# Generated by Django 2.0.7 on 2019-06-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_auto_20190619_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubs',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
