# Generated by Django 2.0.7 on 2019-06-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_pubs_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
