# Generated by Django 2.0.7 on 2019-06-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_auto_20190625_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubs',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
