# Generated by Django 2.0.7 on 2019-06-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_auto_20190626_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='book',
        ),
    ]
