# Generated by Django 2.0.7 on 2019-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_remove_hotels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='cost',
            field=models.CharField(max_length=100),
        ),
    ]
