# Generated by Django 2.0.7 on 2019-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0016_auto_20190626_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='star',
            field=models.CharField(max_length=100),
        ),
    ]
